# Generated by Django 4.2.1 on 2023-05-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozetka_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.AlterModelOptions(
            name='keywords',
            options={'verbose_name': 'KeyWord', 'verbose_name_plural': 'KeyWords'},
        ),
        migrations.AlterField(
            model_name='keywords',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
