# Generated by Django 4.2.1 on 2023-05-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rozetka_admin', '0003_productinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='pure_price',
        ),
    ]
